### ISSUE TITLE
How do I put the project together?

### ISSUE THREAD

**Issue by craftworkgames** [Geaz/SharpDox.Plugins.Html#14]
I grabbed a copy of the dev branch of the HTML plugin and everything builds. Now I'm wondering what to do next?

Is there some process you use to put the plugins with the core. Do we just cobble it together manually before release?  Is there some way to test it all out of Visual Studio?

I'm just curious how you do it. Thanks.

**Comment by Geaz** [comment]
Hi!

In fact this is one of the few thinks which are not automated at the moment.
Usual I take the two packages created by AppVeyor (Core & HTML Plugin) and merge them, together with a fresh generated chm documentation, manually into a new release package.
