### ISSUE TITLE
Links in documentation comments

### ISSUE THREAD

**Issue by Lowcase** [Geaz/SharpDox.Plugins.Html#15]
When I create comment like this

    /// <summary>
    /// Works with <see cref="SomeNameSpace.ClassName"/>.
    /// </summary>

I would expect that link to the class `ClassName` will be generated. But there is only its name.

I tried it also like this

    /// <summary>
    /// Works with [ClassName]({{type-link:SomeNameSpace.ClassName}}).
    /// </summary>

This will correctly parse the Markdown syntax and creates link, but the `{{type-link:SomeNameSpace.ClassName}}` is not transformed to url.

It would be great if these links will be generated also for `example` and `remarks` sections and if it would be possible to generate link to article.

**Comment by Geaz** [comment]
Thanks for your comment. WIll take this onto the list for the next release!

**Comment by Geaz** [comment]
Fixed in new html exporter - will release it soon.
